/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],
	
    //未分类：
	"对敌方造成": "inflict on the enemy",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",
	"": "",

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$\$/,
	/^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,

];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
	[/^(\d+) 物理伤害$/, ' $1 Physical Damage'],
	[/^(\d+) 魔法伤害$/, ' $1 Magic Damage'],
	[/^x 魔法伤害$/, ' x Magic Damage'],
	[/^3x\+(\d+) 魔法伤害$/, ' 3x+$1 Magic Damage'],
	[/^移除$/, 'REMOVE '],
	[/^当前恢复量$/, 'current Restoration'],
	[/^现在能造成$/, 'can now deal'],
	[/^永久移除这张卡$/, 'and permanently removing this card'],
	
	[/^对敌方造成 (\d+) 物理伤害$/, 'inflict on the enemy $1 Physical Damage'],
	[/^增加 (\d+) 护甲$/, 'get $1 Armor'],
	[/^恢复 (\d+) 血,获得 (\d+) 恢复$/, 'restore $1 HP,get $2 Restoration'],
	[/^对敌方造成 (\d+) 魔法伤害$/, 'inflict on the enemy $1 Magic Damage'],
	[/^先获得 (\d+) 智慧,再增加 (\d+) 体力, (\d+) 魔力$/, 'gain $1 Wisdom first, then increase $2 Stamina, $3 Mana'],
	[/^恢复 (\d+) 魔力$/, 'get $1 mana'],
	[/^(\d+)次$/, ' $1 times'],
	[/^获得 (\d+) 力量$/, 'get $1 Strength'],
	[/^给敌方 (\d+) 中毒$/, 'Poison the enemy $1'],
	[/^给敌方 (\d+) 感染,我方 (\d+) 感染$/, 'Infection $1 the enemy and $2 you'],
	[/^抽一张牌,恢复 (\d+) 体力,如果有智慧效果则再触发一次$/, 'draw a card to restore $1 Stamina, and execute it again if there is an Wisdom effect'],
	[/^并附带 (\d+) 眩晕$/, ' with an incidental $1 stun'],
	[/^并获得 (\d+) 回旋镖$/, ' and get $1 boomerang'],
	[/^和$/, ' and'],
	[/^恢复 (\d+) 体力,(\d+) 魔力和 (\d+) 血,造成$/, 'restores $1 Stamina, $2 Mana and $3 HP, deal'],
	[/^,给敌方恢复 (\d+) 血,自己减少 (\d+) 血$/, ' restoring $1 HP to the enemy and reducing $2 HP to itself'],
	[/^,获得 (\d+) 魔力枯竭.给敌方 (\d+) 焱$/, ' and give $2 Mana Depletion. give the enemy $1 Firple'],
	[/^造成$/, 'deal'],
	[/^,敌方获得 (\d+) 魔力枯竭$/, ', enemy gains $1 Mana Depletion'],
	[/^,获得 (\d+) 魔力枯竭$/, ', gain $1 Mana Depletion'],
	[/^恢复 (\d+) 体力$/, 'gain $1 Stamina'],
	[/^每有一张阻梦在手上就少抽一种牌$/, 'Draw one less card every time you have a "block dream" in your hand'],
	[/^使敌人中毒层数翻倍,抽(\d+)张牌$/, 'doubles the number of enemy Poison levels and draws $1 cards'],
	[/^为敌人添加(\d+)层中毒,然后恢复等同于敌人中毒层数的生命值$/, 'adds $1 levels of Poison to enemies, and then restores HP equivalent to the number of levels Poison by enemies'],
	[/^为敌人添加(\d+)层中毒,如果敌人中毒层数≥(\d+)则抽(\d+)张牌$/, 'adds $1 levels Poison to enemies, and draws $3 cards if the enemy poisons levels ≥ $2.'],
	[/^清除敌人所有中毒层数,每清除(\d+)层造成$/, 'clears all Poison levels of an enemy, deal '],
	[/^先将一张当前墓地里最多的牌的复制至手上$/, 'copy the most cards in the current graveyard to the hand'],
	[/^恢复自己损失血量\/(\d+)的生命$/, 'restores the loss of HP \/ $1 of HP'],
	[/^将手牌移回牌库并重新抽取等量的手牌且每移回一张牌\+(\d+)护甲$/, 'the hand cards moves back to the deck and the same amount of hand cards is draw again, with each move back to one card \+ $1 Armor'],
	[/^min\(\(自己损失血量\*敌方损失血量\)\/(\d+)的物理伤害,(\d+)\)$/, 'min ((loss of health by oneself \* enemy loss of health)\/ $1, $2) Physical Damage'],
	[/^(\d+)\*持有手牌的物理伤害$/, ' $1 \*  holding hand cards Physical Damage'],
	[/^获得(\d+)魔力再生效果$/, 'gain $1 Mana Regeneration'],
	[/^恢复(\d+)血,获得 (\d+) 恢复$/, 'restore $1 HP, gain $2 Restoration'],
	[/^恢复(\d+)血并获得(\d+)恢复,(\d+)护甲$/, 'Restore $1 HP and get $2 Restoration, $3 Armor'],
	[/^将手上所有的牌移到墓地并获得等量的布朗魔术$/, 'move all the cards in your hand to the graveyard and get an equal amount of Brown Magic'],
	[/^随机获得以下效果中的其中二个①获得(\d+)力量②获得(\d+)减伤③获得(\d+)体力$/, 'two of the following effects are randomly obtained \(1\) get $1 Strength \(2\) get $2 Damage Reduction \(3\) get $3 Stamina'],
	[/^按降低的比例重新分配血,魔力,体力$/, 'redistribute HP, Mana, Stamina in reduced proportions'],
	[/^使墓地中的牌\*(\d+)$/, 'make the cards in the graveyard \* $1'],
	[/^移除任意最多(\d+)张牌$/, 'remove any of the most $1 cards'],
	[/^15\%拥有的\$的物理伤害$/, '15\% of the Physical Damage of money'],
	[/^,并永久吸取同等血量上限$/, ' and permanently draws the equivalent HP upper limit'],
	[/^恢复(\d+)法力$/, 'restore $1 Mana'],
	[/^使用后开始记录,之后本回合你受到\/造成的伤害都会增加到效果凝血,回合结束取消记录$/, 'after use, the recording begins, after which the damage you take or deal will increase to the effect of Blood Clotting, and the end of the turn will cancel the record'],
	[/^恢复(\d+)血和(\d+)体力$/, 'restore $1 HP and $2 Stamina'],
	[/^50\%获得抽取(\d+)张卡,50\%减去(\d+)血$/, '50% get draw $1 cards, 50% minus $2 blood'],
	[/^血量低于5\%时可以使用,造成$/, 'can be use when the health is less than 5\%, deal'],
	[/^获得(\d+)护甲$/, 'get $1 Armor'],
	[/^50\%给敌方\+(\d+)感染,50\%给我方\+(\d+)感染$/, '50% to enemy \+ $1 Infection, 50% to player \+ $2 Infection'],
	[/^获得(\d+)防御,(\d+)易伤$/, 'get $1 Defense, $2 Vulnerable'],
	[/^恢复(\d+)血$/, 'restore $1 HP'],
	[/^(\d+)\%造成$/, '$1% deal'],
	[/^,(\d+)\%造成$/, ',$1% deal'],
	[/^在手牌中添加一张蔓延,此卡不会使用后进入墓地$/, 'add a "spread" to your hand cards, and this card will not be used after to the graveyard'],
	[/^恢复\[\(当前血\*当前魔力\*当前体力\)\/(\d+)\]\%的血,魔力,体力$/, 'restore \[\(current HP \*current Mana\*current Stamina)\/ $1\] \% of HP, Mana, Stamina'],
	[/^恢复层数\*(\d+),恢复恢复层数的血量$/, 'number of Restoration Levels \* $1, the amount of HP recovered from the number of Restoration levels'],

	[/^消耗:(\d+) 血$/, 'consume:$1 HP'],
	[/^消耗:(\d+) 魔力$/, 'consume:$1 Mana'],
	[/^消耗:x 魔力$/, 'consume:x Mana'],
	[/^消耗:(\d+) 体力$/, 'consume:$1 Stamina'],
	[/^消耗:(\d+)\% \$$/, 'consume:$1% $'],
	[/^消耗:(\d+) 体力,(\d+) 魔力$/, 'consume:$1 Stamina, $2 Mana'],
	[/^消耗:(\d+) 体力,(\d+) 魔力,(\d+) 血$/, 'consume:$1 Stamina, $2 Mana, $3 HP'],
	[/^消耗:无$/, 'consume:None'],
	
	[/^血量 (\d+) \/ (\d+)$/, 'HP $1 \/ $2'],
	[/^魔力 (\d+) \/ (\d+)$/, 'Mana $1 \/ $2'],
	[/^体力 (\d+) \/ (\d+)$/, 'Stamina $1 \/ $2'],
	[/^攻击 (\d+)$/, 'Damage $1'],
	
	[/^护甲 (\d+)$/, 'Armor $1'],
	[/^(\d+)护甲$/, '$1Armor'],
	[/^智慧 (\d+)$/, 'Wisdom $1'],
	[/^(\d+)智慧$/, '$1Wisdom'],
	[/^恢复 (\d+)$/, 'Restoration $1'],
	[/^(\d+)恢复$/, '$1Restoration'],
	[/^力量 (\d+)$/, 'Strength $1'],
	[/^(\d+)力量$/, '$1Strength'],
	[/^中毒 (\d+)$/, 'Poison $1'],
	[/^(\d+)中毒$/, '$1Poison'],
	[/^感染 (\d+)$/, 'Infection $1'],
	[/^(\d+)感染$/, '$Infection'],
	[/^眩晕 (\d+)$/, 'Vertigo $1'],
	[/^(\d+)眩晕$/, '$1Vertigo'],
	[/^魔力枯竭 (\d+)$/, 'Mana Depletion $1'],
	[/^(\d+)魔力枯竭$/, '$1Mana Depletion'],
	[/^焱 (\d+)$/, 'Firple $1'],
	[/^(\d+)焱$/, '$1Firple'],
	[/^炎 (\d+)$/, 'Firble $1'],
	[/^(\d+)炎$/, '$1Firble'],
	[/^焕 (\d+)$/, 'Brilliance $1'],
	[/^(\d+)焕$/, '$1Brilliance'],
	[/^布朗魔术 (\d+)$/, 'Brown Magic $1'],
	[/^(\d+)布朗魔术$/, '$1Brown Magic'],
	[/^混乱 (\d+)$/, 'Confusion $1'],
	[/^(\d+)混乱$/, '$1Confusion'],
	[/^魔力再生 (\d+)$/, 'Mana Regeneration $1'],
	[/^(\d+)魔力再生$/, '$1Mana Regeneration'],
	[/^减伤 (\d+)$/, 'Damage Reduction $1'],
	[/^(\d+)减伤$/, '$1Damage Reduction'],
	[/^凝血 (\d+)$/, 'Blood Clotting $1'],
	[/^(\d+)凝血$/, '$1Blood Clotting'],
	[/^易伤 (\d+)$/, 'Vulnerable $1'],
	[/^(\d+)易伤$/, '$1Vulnerable'],
	
	[/^攻击$/, 'Attack'],
	[/^防御$/, 'Defense'],
	[/^治疗$/, 'Treat'],
	[/^魔力飞弹$/, 'Magic Missile'],
	[/^冥想$/, 'Meditation'],
	[/^魔力再生$/, 'Source Of Magic'],
	[/^连斩$/, 'Continuous cutting'],
	[/^愤怒$/, 'Angry'],
	[/^传染$/, 'Contagion'],
	[/^病原体$/, 'Pathogen'],
	[/^思考$/, 'Think'],
	[/^重击$/, 'Thump'],
	[/^回旋镖$/, 'Boomerang'],
	[/^无中生有$/, 'Come out of thin air'],
	[/^烨$/, 'Bright sunlight'],
	[/^灵能冲击$/, 'Psionic strike'],
	[/^破魂打击$/, 'Soul breaking strike'],
	[/^魔能调换$/, 'Magic power exchange'],
	[/^阻梦$/, 'Block Dream'],
	[/^毒素扩散$/, 'Toxin diffusion'],
	[/^血清$/, 'Serum'],
	[/^隐秘扩散$/, 'Covert diffusion'],
	[/^病毒爆发$/, 'Virus outbreak'],
	[/^墓地增生$/, 'Cemetery hyperplasia'],
	[/^肉体再生$/, 'Body hyperplasia'],
	[/^重构$/, 'Restructure'],
	[/^嗜血斩$/, 'Bloodthirsty chop'],
	[/^自信$/, 'Self-confidence'],
	[/^魔力源泉$/, 'Wizards Well'],
	[/^治疗术$/, 'HEAL'],
	[/^绷带$/, 'Bandage'],
	[/^卡牌魔法$/, 'Card Magic'],
	[/^献祭$/, 'Sacrifice'],
	[/^天平$/, 'Balance'],
	[/^墓地衍生$/, 'Cemetery derivation'],
	[/^滴血$/, 'Dripping blood'],
	[/^破财消灾$/, 'Spend money to eliminate disasters'],
	[/^灵魂吸取$/, 'Soul reaping'],
	[/^魔法结晶$/, 'Magic crystal'],
	[/^提取器$/, 'Extractor'],
	[/^应急干粮$/, 'Emergency food'],
	[/^老千$/, 'Cheat'],
	[/^破釜沉舟$/, 'Fight to win or die'],
	[/^能量护盾$/, 'Energy shield'],
	[/^不定性病毒$/, 'Indeterminate virus'],
	[/^格挡$/, 'Parry'],
	[/^急救$/, 'First aid'],
	[/^背刺$/, 'Backstab'],
	[/^蔓延$/, 'Spread'],
	[/^聚集$/, 'Gather'],
	[/^再生$/, 'Regeneration'],
	
	[/^获得攻击$/, 'Award Attack'],
	[/^获得防御$/, 'Award Defense'],
	[/^获得治疗$/, 'Award Treat'],
	[/^获得魔力飞弹$/, 'Award Magic Missile'],
	[/^获得冥想$/, 'Award Meditation'],
	[/^获得魔力再生$/, 'Award Source Of Magic'],
	[/^获得连斩$/, 'Award Continuous cutting'],
	[/^获得愤怒$/, 'Award Angry'],
	[/^获得传染$/, 'Award Contagion'],
	[/^获得病原体$/,'Award Pathogen'],
	[/^获得思考$/, 'Award Think'],
	[/^获得重击$/, 'Award Thump'],
	[/^获得回旋镖$/, 'Award Boomerang'],
	[/^获得无中生有$/, 'Award Come out of thin air'],
	[/^获得烨$/, 'Award Bright sunlight'],
	[/^获得灵能冲击$/, 'Award Psionic strike'],
	[/^获得破魂打击$/, 'Award Soul breaking strike'],
	[/^获得魔能调换$/, 'Award Magic power exchange'],
	[/^获得毒素扩散$/, 'Award Toxin diffusion'],
	[/^获得血清$/, 'Award Serum'],
	[/^获得隐秘扩散$/, 'Award Covert diffusion'],
	[/^获得病毒爆发$/, 'Award Virus outbreak'],
	[/^获得墓地增生$/, 'Award Cemetery hyperplasia'],
	[/^获得肉体增生$/, 'Award Body hyperplasia'],
	[/^获得重构$/, 'Award Restructure'],
	[/^获得嗜血斩$/, 'Award Bloodthirsty chop'],
	[/^获得自信$/, 'Award Self-confidence'],
	[/^获得魔力源泉$/, 'Award Wizards Well'],
	[/^获得治疗术$/, 'Award HEAL'],
	[/^获得绷带$/, 'Award Bandage'],
	[/^获得卡牌魔法$/, 'Award Card Magic'],
	[/^获得献祭$/, 'Award Sacrifice'],
	[/^获得天平$/, 'Award Balance'],
	[/^获得墓地衍生$/, 'Award Cemetery derivation'],
	[/^获得滴血$/, 'Award Dripping blood'],
	[/^获得破财消灾$/, 'Award Spend money to eliminate disasters'],
	[/^获得灵魂吸取$/, 'Award Soul reaping'],
	[/^获得魔法结晶$/, 'Award Magic crystal'],
	[/^获得提取器$/, 'Award Extractor'],
	[/^获得应急干粮$/, 'Award Emergency food'],
	[/^获得老千$/, 'Award Cheat'],
	[/^获得破釜沉舟$/, 'Award Fight to win or die'],
	[/^获得能量护盾$/, 'Award Energy shield'],
	[/^获得不定性病毒$/, 'Award Indeterminate virus'],
	[/^获得格挡$/, 'Award Parry'],
	[/^获得急救$/, 'Award First aid'],
	[/^获得背刺$/, 'Award Backstab'],
	[/^获得蔓延$/, 'Award Spread'],
	[/^获得聚集$/, 'Award Gather'],
	[/^获得再生$/, 'Award Regeneration'],
	
	[/^保存$/, 'save'],
	[/^材质: 经典$/, 'Theme: Classical'],
	[/^材质: 纯白$/, 'Theme: Pure white'],
	[/^材质: 亮蓝$/, 'Theme: Bright blue'],
	[/^材质: 海蓝$/, 'Theme: Navy blue'],
	[/^材质: 游戏树特殊页面$/, 'Theme: Classical'],
	[/^文字荧光: 开$/, 'fluorescence: Open'],
	[/^文字荧光: 关$/, 'The special page in The-Game-Tree' ],
	[/^返回游戏$/, 'Return to game'],
	[/^返回$/, 'Return'],
	[/^存档$/, 'File'],
	[/^画面$/, 'Frame'],
	[/^操作$/, 'Operation'],
	[/^硬重置$/, 'HardRest'],
	[/^软重置$/, 'SoftRest'],
	[/^按住shift点击永久显示悬浮框: 开$/, 'Tap the shift and click to display Suspension window foever: Open'],
	[/^按住shift点击永久显示悬浮框: 关$/, 'Tap the shift and click to display Suspension window foever: Close'],
	
	[/^把鼠标对准我查看全属性/, 'Let your mouse here to check all the attribute'],
	[/^tip:你有5种不同的背景可以换(包括亮色),当前背景:/, 'tip:You have five kinds of backcolor to change(include Bright color),and now the backcolor is:'],
	[/^经典/, 'Classical'],
	[/^纯白/, 'Pure white'],
	[/^亮蓝/, 'Bright blue'],
	[/^海蓝/, 'Navy blue'],
	[/^QQ群:688646311\|左上角设置,信息,捐助\|右上角版本,图鉴,背包,成就$/, 'QQ group(A software in China):688646311|Upper left corner:setting,information and donation|Upper right corner:version,illustrated,backpacker and Achievement'],
	[/^加载中$/, 'LOADING'],
	[/^右上角分别是版本,图鉴,背包.$/, 'Upper left corner:setting,information and donation.'],
	[/^左上角分别是设置,信息,捐助.$/, 'Upper right corner:version,illustrated and backpacker.'],
	[/^QQ群:688646311$/, 'QQ group:688646311'],
	[/^你的最高分是:(\d+).你上次的得分是:(\d+).$/, 'Your highest score is $1.Last time your score is $2'],
	[/^你在层(\d+)/, 'Now,you are in level $1'],
	[/^怪物会随着关卡提升越来越强./, 'The monster will become stronger and stronger with the levels you have pathed'],
	
	[/^开始!$/, 'Start'],
	[/^下一回合!$/, 'Next round'],
	[/^3体力$/, '3 Stamina'],
	[/^÷2护甲$/, '÷2 Armor'],
	[/^钱!$/, 'Money!'],
	[/^牌!$/, 'Card!'],
	[/^宝箱!$/, 'Treasure chest!'],
	[/^你只可以选择其中的一个$/, 'You can only choose one of them'],
	[/^烤火$/, 'Fire'],
	[/^这使你充满决心$/, 'It fills you with determination'],
	
	[/^商店$/, 'Shore'],
	[/^怪物$/, 'Monster'],
	[/^精英怪$/, 'Elite Monster'],
	[/^宝箱$/, 'Chest'],
	[/^营火$/, 'Campfire'],
	[/^黑洞$/, 'Black Hole'],
	[/^白洞$/, 'White Hole'],
]); 
